# Change baseurl before deploy
baseurl      = "https://blog.fahdlabs.com/"
languageCode = "ar"
title        = "FahdLABs | مختّبر فهد"
enableRobotsTXT = "true"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "ar"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "fahdlabs"

[pagination]
    pagerSize = 5
