# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "youtube"
    name       = "YouTube"
    url        = "https://www.youtube.com/@fahdlabs"

    [social.params]
        icon = "brand-youtube"

[[social]]
    identifier = "twitter"
    name       = "X (Twitter)"
    url        = "https://x.com/fahdlabs"

    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "instagram"
    name       = "Instagram"
    url        = "https://www.instagram.com/fahdlabs"

    [social.params]
        icon = "brand-instagram"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/fahdlabs"

    [social.params]
        icon = "brand-github"
