# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
description  = "FahdLABs | Ù…Ø®ØªÙ‘Ø¨Ø± ÙÙ‡Ø¯ - Ù‡Ù†Ø§ Ø£Ø´Ø§Ø±Ùƒ ÙƒÙ„ Ø´ÙŠØ¡ ØªÙ‚Ù†ÙŠ ÙŠØ´Ø¯Ù†ÙŠ: Ù…Ù† Windows ÙˆLinux Ø¥Ù„Ù‰ AIØŒ Ø§Ù„Ø£Ø¯ÙˆØ§ØªØŒ Ø§Ù„Ù…Ø±Ø§Ø¬Ø¹Ø§ØªØŒ ÙˆØªØ¬Ø§Ø±Ø¨ Ø­Ù‚ÙŠÙ‚ÙŠØ© Ø¨Ø¯ÙˆÙ† Ù„Ù ÙˆØ¯ÙˆØ±Ø§Ù†."
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon-fhd.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = "FahdLABs - ØªÙ‚Ù†ÙŠØ© Ø¹Ù„Ù‰ Ø§Ù„Ø³Ø±ÙŠØ¹ ÙˆØ¨Ø£Ø³Ù„ÙˆØ¨ Ø¨Ø³ÙŠØ·: Ù†Ø¬Ø±Ø¨ØŒ Ù†Ø¶Ø¨Ø·ØŒ ÙˆÙ†Ø´Ø§Ø±Ùƒ Ø§Ù„Ù„ÙŠ ÙŠÙ†ÙØ¹."

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "ğŸ‘º"
    subtitle = "ÙŠØ§ Ù‡Ù„Ø§! Ù‡Ø°Ù‡ Ù…Ø¯ÙˆÙ†Ø© FahdLABs. ÙƒÙ„ Ù…Ø§ ÙŠØ­Ù…Ù‘Ø³Ù†ÙŠ ÙÙŠ Ø§Ù„ØªÙ‚Ù†ÙŠØ© Ø¨ØªØ­ØµÙ„Ù‡ Ù‡Ù†Ø§: WindowsØŒ LinuxØŒ AIØŒ Ù…Ø±Ø§Ø¬Ø¹Ø§ØªØŒ Ø£Ø¯ÙˆØ§ØªØŒ ÙˆØªØ¬Ø§Ø±Ø¨ Ø¹Ù…Ù„ÙŠØ© Ù…Ù† Ø§Ù„ÙˆØ§Ù‚Ø¹."
    avatar   = "img/avatar-fhd.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Ù…Ø±Ø®Ù‘Øµ ØªØ­Øª CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        # { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = "@fahdlabs"
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "disqus"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.
